<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Broker;

class BrokerSeeder extends Seeder
{
    public function run(): void
    {
        $brokers = [
            ['slug' => 'universal-broker', 'name' => ['ru' => 'Universal Broker', 'uz' => 'Universal Broker', 'en' => 'Universal Broker'], 'description' => ['ru' => 'Ведущая брокерская компания с 15-летним опытом на биржевом рынке Узбекистана. Предоставляем полный спектр услуг.', 'uz' => 'O\'zbekiston birja bozorida 15 yillik tajribaga ega yetakchi brokerlik kompaniyasi.', 'en' => 'Leading brokerage company with 15 years of experience in the Uzbekistan exchange market.'], 'license_number' => 'BR-2024-001', 'phone' => '+998 71 255-10-10', 'email' => 'info@universalbroker.uz', 'website' => 'https://universalbroker.uz', 'address' => ['ru' => 'г. Ташкент, ул. Амира Тимура, 15', 'uz' => 'Toshkent sh., Amir Temur ko\'ch., 15', 'en' => 'Tashkent, Amir Temur str., 15'], 'rating' => 5, 'tags' => ['Хлопок', 'Зерновые', 'Металлы'], 'is_active' => true, 'is_featured' => true, 'is_top' => true, 'is_verified' => true, 'sort_order' => 1],
            ['slug' => 'silk-road-trading', 'name' => ['ru' => 'Silk Road Trading', 'uz' => 'Silk Road Trading', 'en' => 'Silk Road Trading'], 'description' => ['ru' => 'Специализируемся на торговле текстильным сырьём и готовой продукцией.', 'uz' => 'To\'qimachilik xom ashyosi va tayyor mahsulotlar savdosiga ixtisoslashgan.', 'en' => 'Specialized in textile raw materials and finished products trading.'], 'license_number' => 'BR-2024-002', 'phone' => '+998 71 200-20-20', 'email' => 'trade@silkroad.uz', 'website' => 'https://silkroad-trading.uz', 'address' => ['ru' => 'г. Ташкент, пр. Навои, 42', 'uz' => 'Toshkent sh., Navoiy xiyoboni, 42', 'en' => 'Tashkent, Navoi ave., 42'], 'rating' => 5, 'tags' => ['Текстиль', 'Шёлк', 'Хлопок'], 'is_active' => true, 'is_featured' => true, 'is_top' => true, 'is_verified' => true, 'sort_order' => 2],
            ['slug' => 'agro-invest', 'name' => ['ru' => 'АгроИнвест', 'uz' => 'AgroInvest', 'en' => 'AgroInvest'], 'description' => ['ru' => 'Брокерская компания, специализирующаяся на сельскохозяйственной продукции.', 'uz' => 'Qishloq xo\'jaligi mahsulotlariga ixtisoslashgan brokerlik kompaniyasi.', 'en' => 'Brokerage company specializing in agricultural products.'], 'license_number' => 'BR-2024-003', 'phone' => '+998 71 300-30-30', 'email' => 'info@agroinvest.uz', 'address' => ['ru' => 'г. Самарканд, ул. Регистан, 5', 'uz' => 'Samarqand sh., Registon ko\'ch., 5', 'en' => 'Samarkand, Registan str., 5'], 'rating' => 4, 'tags' => ['Зерновые', 'Фрукты', 'Овощи'], 'is_active' => true, 'is_featured' => false, 'is_top' => false, 'is_verified' => true, 'sort_order' => 3],
            ['slug' => 'metal-trade-uz', 'name' => ['ru' => 'MetalTrade UZ', 'uz' => 'MetalTrade UZ', 'en' => 'MetalTrade UZ'], 'description' => ['ru' => 'Лидер в сфере торговли цветными и чёрными металлами на бирже.', 'uz' => 'Birjada rangli va qora metallar savdosida yetakchi.', 'en' => 'Leader in non-ferrous and ferrous metals exchange trading.'], 'license_number' => 'BR-2024-004', 'phone' => '+998 71 400-40-40', 'email' => 'info@metaltrade.uz', 'address' => ['ru' => 'г. Ташкент, ул. Мустакиллик, 77', 'uz' => 'Toshkent sh., Mustaqillik ko\'ch., 77', 'en' => 'Tashkent, Mustaqillik str., 77'], 'rating' => 4, 'tags' => ['Медь', 'Золото', 'Алюминий'], 'is_active' => true, 'is_featured' => false, 'is_top' => false, 'is_verified' => true, 'sort_order' => 4],
            ['slug' => 'energy-resources', 'name' => ['ru' => 'Energy Resources', 'uz' => 'Energy Resources', 'en' => 'Energy Resources'], 'description' => ['ru' => 'Специализация на нефтепродуктах и энергоресурсах.', 'uz' => 'Neft mahsulotlari va energiya resurslariga ixtisoslashgan.', 'en' => 'Specialization in petroleum products and energy resources.'], 'license_number' => 'BR-2024-005', 'phone' => '+998 71 500-50-50', 'email' => 'info@energyres.uz', 'address' => ['ru' => 'г. Бухара, ул. Центральная, 10', 'uz' => 'Buxoro sh., Markaziy ko\'ch., 10', 'en' => 'Bukhara, Central str., 10'], 'rating' => 3, 'tags' => ['Нефть', 'Газ', 'Бензин'], 'is_active' => true, 'is_featured' => false, 'is_top' => false, 'is_verified' => false, 'sort_order' => 5],
            ['slug' => 'global-commodity', 'name' => ['ru' => 'Global Commodity', 'uz' => 'Global Commodity', 'en' => 'Global Commodity'], 'description' => ['ru' => 'Международная брокерская компания с представительством в Ташкенте.', 'uz' => 'Toshkentda vakolatxonasi bor xalqaro brokerlik kompaniyasi.', 'en' => 'International brokerage company with a representative office in Tashkent.'], 'license_number' => 'BR-2024-006', 'phone' => '+998 71 600-60-60', 'email' => 'info@globalcommodity.uz', 'website' => 'https://globalcommodity.uz', 'address' => ['ru' => 'г. Ташкент, ул. Шота Руставели, 33', 'uz' => 'Toshkent sh., Shota Rustaveli ko\'ch., 33', 'en' => 'Tashkent, Shota Rustaveli str., 33'], 'rating' => 5, 'tags' => ['Хлопок', 'Нефть', 'Металлы', 'Зерновые'], 'is_active' => true, 'is_featured' => true, 'is_top' => true, 'is_verified' => true, 'sort_order' => 6],
        ];

        foreach ($brokers as $b) {
            Broker::updateOrCreate(['slug' => $b['slug']], $b);
        }
    }
}
