<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\News;

class NewsSeeder extends Seeder
{
    public function run(): void
    {
        $news = [
            ['slug' => 'cotton-trading-record-2026', 'category_id' => 1, 'title' => ['ru' => 'Рекордный объём торгов хлопковым волокном', 'uz' => 'Paxta tolasi savdosida rekord hajm', 'en' => 'Record cotton fiber trading volume'], 'excerpt' => ['ru' => 'На RUAPB зафиксирован рекордный объём торгов хлопком за I квартал 2026 года.', 'uz' => '2026 yilning I choragi uchun UZEX paxta savdosida rekord qayd etildi.', 'en' => 'UZEX recorded a record volume of cotton trading for Q1 2026.'], 'content' => ['ru' => '<p>Сегодня на Узбекской республиканской товарно-сырьевой бирже зафиксирован рекордный объём торгов хлопковым волокном. Общий объём сделок составил более 150 миллиардов сумов.</p><p>По словам экспертов, рост объёмов связан с увеличением спроса на международных рынках и улучшением качества узбекского хлопка.</p>', 'uz' => '<p>Bugun UZEX birjasida paxta tolasi savdosida rekord hajm qayd etildi.</p>', 'en' => '<p>Today UZEX recorded a record volume of cotton trading.</p>'], 'is_published' => true, 'is_featured' => true, 'published_at' => now()->subDays(1)],
            ['slug' => 'new-trading-rules-2026', 'category_id' => 3, 'title' => ['ru' => 'Вступили в силу новые правила биржевой торговли', 'uz' => 'Birja savdosining yangi qoidalari kuchga kirdi', 'en' => 'New trading rules come into effect'], 'excerpt' => ['ru' => 'С 1 февраля 2026 года вступили в силу обновлённые правила торговли на RUAPB.', 'uz' => '2026 yil 1 fevraldan UZEX savdo qoidalari yangilandi.', 'en' => 'Updated UZEX trading rules came into effect from February 1, 2026.'], 'content' => ['ru' => '<p>Обновлённые правила торговли включают ряд важных изменений, направленных на повышение прозрачности и защиту интересов участников.</p>', 'uz' => '<p>Yangilangan qoidalar shaffoflikni oshirish va ishtirokchilar manfaatlarini himoya qilishga qaratilgan.</p>', 'en' => '<p>Updated rules include important changes aimed at increasing transparency.</p>'], 'is_published' => true, 'is_featured' => false, 'published_at' => now()->subDays(2)],
            ['slug' => 'quarterly-report-q4-2025', 'category_id' => 2, 'title' => ['ru' => 'Анализ итогов торгов за IV квартал 2025 года', 'uz' => '2025 yil IV chorak savdo natijalari tahlili', 'en' => 'Q4 2025 trading results analysis'], 'excerpt' => ['ru' => 'Аналитический обзор результатов биржевых торгов за последний квартал 2025 года.', 'uz' => '2025 yilning oxirgi choragi birja savdolari tahlili.', 'en' => 'Analytical review of exchange trading results for Q4 2025.'], 'content' => ['ru' => '<p>В IV квартале 2025 года общий объём торгов на RUAPB составил 2.5 трлн сумов, что на 15% больше аналогичного периода прошлого года.</p>', 'uz' => '<p>2025 yilning IV choragida UZEX umumiy savdo hajmi 2.5 trln so\'mni tashkil etdi.</p>', 'en' => '<p>In Q4 2025, total UZEX trading volume amounted to 2.5 trillion soums.</p>'], 'is_published' => true, 'is_featured' => true, 'published_at' => now()->subDays(3)],
            ['slug' => 'international-conference-2026', 'category_id' => 4, 'title' => ['ru' => 'Международная конференция по биржевой торговле', 'uz' => 'Birja savdosi bo\'yicha xalqaro konferensiya', 'en' => 'International Conference on Exchange Trading'], 'excerpt' => ['ru' => 'RUAPB проводит международную конференцию с участием экспертов из 15 стран.', 'uz' => 'UZEX 15 davlatdan ekspertlar ishtirokida xalqaro konferensiya o\'tkazadi.', 'en' => 'UZEX hosts international conference with experts from 15 countries.'], 'content' => ['ru' => '<p>В марте 2026 года RUAPB проведёт ежегодную международную конференцию по развитию биржевой торговли в Центральной Азии.</p>', 'uz' => '<p>2026 yil mart oyida UZEX Markaziy Osiyoda birja savdosini rivojlantirish bo\'yicha yillik xalqaro konferensiya o\'tkazadi.</p>', 'en' => '<p>In March 2026, UZEX will host its annual international conference on exchange trading development in Central Asia.</p>'], 'is_published' => true, 'is_featured' => false, 'published_at' => now()->subDays(5)],
            ['slug' => 'digital-platform-launch', 'category_id' => 5, 'title' => ['ru' => 'Запуск новой цифровой платформы RUAPB', 'uz' => 'UZEXning yangi raqamli platformasi ishga tushirildi', 'en' => 'Launch of new UZEX digital platform'], 'excerpt' => ['ru' => 'RUAPB представляет обновлённую цифровую торговую платформу с расширенным функционалом.', 'uz' => 'UZEX kengaytirilgan funksionalga ega yangilangan raqamli savdo platformasini taqdim etadi.', 'en' => 'UZEX presents an updated digital trading platform with expanded functionality.'], 'content' => ['ru' => '<p>Новая платформа обеспечивает более быструю обработку заявок и улучшенный пользовательский интерфейс для всех участников торгов.</p>', 'uz' => '<p>Yangi platforma barcha savdo ishtirokchilari uchun tezroq so\'rov qayta ishlash va yaxshilangan foydalanuvchi interfeysini ta\'minlaydi.</p>', 'en' => '<p>The new platform provides faster order processing and an improved user interface for all trading participants.</p>'], 'is_published' => true, 'is_featured' => true, 'published_at' => now()->subDays(7)],
            ['slug' => 'grain-market-overview', 'category_id' => 2, 'title' => ['ru' => 'Обзор рынка зерновых культур', 'uz' => 'Don ekinlari bozori sharhi', 'en' => 'Grain market overview'], 'excerpt' => ['ru' => 'Еженедельный обзор цен на пшеницу, кукурузу и рис на бирже.', 'uz' => 'Bug\'doy, makkajo\'xori va guruch narxlari haftalik sharhi.', 'en' => 'Weekly review of wheat, corn and rice prices on the exchange.'], 'content' => ['ru' => '<p>На прошедшей неделе цены на пшеницу выросли на 2.3%, кукуруза показала стабильность, а рис подорожал на 1.1%.</p>', 'uz' => '<p>O\'tgan haftada bug\'doy narxi 2.3% ga oshdi, makkajo\'xori barqaror bo\'ldi, guruch esa 1.1% ga qimmatlashdi.</p>', 'en' => '<p>Last week wheat prices rose by 2.3%, corn remained stable, and rice increased by 1.1%.</p>'], 'is_published' => true, 'is_featured' => false, 'published_at' => now()->subDays(4)],
        ];

        foreach ($news as $item) {
            News::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
